process.env.EXTENSIOM_MARKETPLACE_ACCOUNT_ID = 'UmNbWUNFYqj-l_Otk_uo70JZ';
process.env.EXTENSIOM_MARKETPLACE_MASTER_KEY = 'VC7IyB0TTgaNiwWvFiPMNAl9';
process.env.EXTENSIOM_MARKETPLACE_ENPOINT = ''
process.env.NPM_CLIENT = 'npm'
